### ISSUE TITLE
use http_proxy/https_proxy if env vars are defined

### ISSUE THREAD

**Issue by JamesClonk** [cloudfoundry-incubator/bosh-workspace#63]
bosh-workspace should use the env vars http_proxy and https_proxy during `prepare deployment` when fetching a release or a stemcell, so it can be used in an enviroment without direct internet access, where everything goes through an http proxy.

**Comment by fearoffish** [comment]
After experimenting a little, it seems you need multiple variables set but this does work already:

```bash
HTTP_PROXY=<proxy url>
HTTPS_PROXY=<proxy url>
http_proxy=<proxy url>
https_proxy=<proxy url>
```

Does this work for you?

**Comment by rkoster** [comment]
@fearoffish have you tested `bosh prepare deployment` as well? Also why do you need the caps version and the lower case version?

**Comment by fearoffish** [comment]
I tested bosh prepare deployment and saw hits to the proxy I was using, I couldn't test it in complete isolation without setting up a complete VPC. The HttpClient library looks for one and libgit looks for the other.

**Comment by fearoffish** [comment]
I did also set:

```
git config --global http.proxy $http_proxy
git config --global https.proxy $https_proxy
```

I don't think this was necessary though.

**Comment by rkoster** [comment]
`bosh prepare deployment` uses [Rugged](https://github.com/libgit2/rugged) which uses `libgit2`. I'm not sure `libgit2` is affected by `git config`.

**Comment by fearoffish** [comment]
It is, according to the issues.

**Comment by rkoster** [comment]
Found the following issues related to rugged proxy support:
Rugged: 
- https://github.com/libgit2/rugged/issues/440

Libgit2: 
- https://github.com/libgit2/libgit2/issues/2555
- https://github.com/libgit2/libgit2/pull/3110

**Comment by fearoffish** [comment]
Two of those are windows specific. The other references libgit2.  Libgit2 supports the same options as git itself, which are the ones I mentioned. Hence trying it out, seeing it hit the proxy and wondering if it works in a real proxy situation. ;)

**Comment by fearoffish** [comment]
@JamesClonk Have you tried when you set all 4 env vars?

**Comment by JamesClonk** [comment]
@fearoffish, @rkoster  It seems to work only partly, because for some reason bosh-workspace asks for a .credentials file, even when pulling the cf-release from github.

```
[user@host bosh-workspace]$ bundle exec bosh prepare deployment

Fetching release 'cf' to satisfy template references
Authentication is required for: https://github.com/cloudfoundry/cf-release.git
Credentials file does not exist: /home/user/bosh-workspace/.credentials.yml
```

**Comment by longnguyen11288** [comment]
this should be fixed by upgrade of rugged https://github.com/cloudfoundry-incubator/bosh-workspace/pull/65

**Comment by JamesClonk** [comment]
@longnguyen11288 @fearoffish @rkoster Was the newer rugged version supposed to fix the http-proxy or the Credentials file issue?

Unfortunately I can't test the http-proxy, as `bosh prepare deployment` still fails on the .credentials.yml file:
```
$ bundle exec bosh prepare deployment

Fetching release 'cf' to satisfy template references
Authentication is required for: https://github.com/cloudfoundry/cf-release.git
Credentials file does not exist: /home/tmz-mdl-1/bosh-workspace/.credentials.yml
```

used bosh_cli 1.3004.0, rugged 0.23.0b4,  bosh-workspace master branch for this..

**Comment by longnguyen11288** [comment]
hmm do you have `libcurl4-openssl-dev` installed? If it is, rugged uses curl by default which respects https_proxy

**Comment by JamesClonk** [comment]
@longnguyen11288 It's on a redhat machine, I did install `libcurl-devel`. It was the only such package available.
```
$ bundle install
with native extensions  Installing rugged 0.23.0b4
...
```

Still the same problem though. Rugged does not seem to use the http-proxy.

**Comment by rkoster** [comment]
I have verified it works with the latest version
